In [80]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [81]:
print(a.shape)

(2, 3)


In [82]:
print(a.ndim)

2


In [83]:
print(a.itemsize)

8


In [84]:
print(a.dtype)

int64


In [85]:
print(a.nbytes)

48


In [86]:
print(a.size)

6


In [87]:
a=np.array([[1,3,5,7,9],[2,4,6,8,10]])
print(a.ndim)

2


In [88]:
print(a[0,3])

7


In [89]:
a[1,4]=20
print(a)

[[ 1  3  5  7  9]
 [ 2  4  6  8 20]]


In [90]:
a[:,1]=5
print(a)

[[ 1  5  5  7  9]
 [ 2  5  6  8 20]]


In [91]:
a[:,0]=[0,1]
print(a)

[[ 0  5  5  7  9]
 [ 1  5  6  8 20]]


In [92]:
#3D array
b=np.array([[[1,2,3],[7,8,9]],[[4,5,6],[10,11,12]]])
print(b)

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


In [93]:
print(b[0,-1,:])

[7 8 9]


In [94]:
b[1,1,2]=110
print(b[1,1,:])

[ 10  11 110]


In [95]:
b=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[1,3,5,7,9],[2,4,6,8,10]]])
print(b)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  3  5  7  9]
  [ 2  4  6  8 10]]]


In [96]:
b[0,:,1]=20
print(b)

[[[ 1 20  3  4  5]
  [ 6 20  8  9 10]]

 [[ 1  3  5  7  9]
  [ 2  4  6  8 10]]]


In [97]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [98]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [99]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [100]:
x=np.array([[1,3,5],[2,4,6]])
np.full_like(x,6)

array([[6, 6, 6],
       [6, 6, 6]])

In [101]:
np.random.randint(7,9,size=(2,4))

array([[8, 8, 8, 7],
       [8, 7, 8, 7]], dtype=int32)

In [102]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [103]:
r=np.repeat(x,4,axis=1)
print(r)

[[1 1 1 1 3 3 3 3 5 5 5 5]
 [2 2 2 2 4 4 4 4 6 6 6 6]]


In [130]:
output=np.full((5,5),3)
print(output)
z=np.zeros(3,dtype="int32")
print(z)
y=np.zeros(3,dtype='int32')
print(y)
output[1:4,2]=y
output[2,1:4]=z
output[2,2]=9
print(output)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
[0 0 0]
[0 0 0]
[[3 3 3 3 3]
 [3 3 0 3 3]
 [3 0 9 0 3]
 [3 3 0 3 3]
 [3 3 3 3 3]]


In [108]:
p=np.array([[1,2,3],[4,5,6]])
p+2

array([[3, 4, 5],
       [6, 7, 8]])

In [107]:
p-2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [109]:
p*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [113]:
(p/2)

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [114]:
p**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [124]:
a=np.ones((3,2))
b=np.identity(3)
np.matmul(b,a).astype(np.int32)


array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [125]:
np.max(p)

np.int64(6)

In [138]:
p=np.array([[3,5,7],[4,6,8]])
print(np.max(p))
print(np.min(p))
print(np.max(p,axis=0))
print(np.min(p,axis=1))
print(np.sum(p,axis=0))
print(np.sum(p,axis=1))

8
3
[4 6 8]
[3 4]
[ 7 11 15]
[15 18]
